/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard/$guildId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardGuildIdSettingsRouteImport } from './routes/dashboard/$guildId/settings'
import { Route as DashboardGuildIdSchedulingRouteImport } from './routes/dashboard/$guildId/scheduling'
import { Route as DashboardGuildIdOverviewRouteImport } from './routes/dashboard/$guildId/overview'
import { Route as DashboardGuildIdAttendanceRouteImport } from './routes/dashboard/$guildId/attendance'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/dashboard/$guildId',
  path: '/dashboard/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdSettingsRoute =
  DashboardGuildIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdSchedulingRoute =
  DashboardGuildIdSchedulingRouteImport.update({
    id: '/scheduling',
    path: '/scheduling',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdOverviewRoute =
  DashboardGuildIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdAttendanceRoute =
  DashboardGuildIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/dashboard/$guildId/attendance': typeof DashboardGuildIdAttendanceRoute
  '/dashboard/$guildId/overview': typeof DashboardGuildIdOverviewRoute
  '/dashboard/$guildId/scheduling': typeof DashboardGuildIdSchedulingRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/dashboard/$guildId/attendance': typeof DashboardGuildIdAttendanceRoute
  '/dashboard/$guildId/overview': typeof DashboardGuildIdOverviewRoute
  '/dashboard/$guildId/scheduling': typeof DashboardGuildIdSchedulingRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/dashboard/$guildId/attendance': typeof DashboardGuildIdAttendanceRoute
  '/dashboard/$guildId/overview': typeof DashboardGuildIdOverviewRoute
  '/dashboard/$guildId/scheduling': typeof DashboardGuildIdSchedulingRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/$guildId'
    | '/dashboard/$guildId/attendance'
    | '/dashboard/$guildId/overview'
    | '/dashboard/$guildId/scheduling'
    | '/dashboard/$guildId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/$guildId'
    | '/dashboard/$guildId/attendance'
    | '/dashboard/$guildId/overview'
    | '/dashboard/$guildId/scheduling'
    | '/dashboard/$guildId/settings'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/dashboard/$guildId'
    | '/dashboard/$guildId/attendance'
    | '/dashboard/$guildId/overview'
    | '/dashboard/$guildId/scheduling'
    | '/dashboard/$guildId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardGuildIdRoute: typeof DashboardGuildIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/settings': {
      id: '/dashboard/$guildId/settings'
      path: '/settings'
      fullPath: '/dashboard/$guildId/settings'
      preLoaderRoute: typeof DashboardGuildIdSettingsRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/scheduling': {
      id: '/dashboard/$guildId/scheduling'
      path: '/scheduling'
      fullPath: '/dashboard/$guildId/scheduling'
      preLoaderRoute: typeof DashboardGuildIdSchedulingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/overview': {
      id: '/dashboard/$guildId/overview'
      path: '/overview'
      fullPath: '/dashboard/$guildId/overview'
      preLoaderRoute: typeof DashboardGuildIdOverviewRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/attendance': {
      id: '/dashboard/$guildId/attendance'
      path: '/attendance'
      fullPath: '/dashboard/$guildId/attendance'
      preLoaderRoute: typeof DashboardGuildIdAttendanceRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
  }
}

interface DashboardGuildIdRouteChildren {
  DashboardGuildIdAttendanceRoute: typeof DashboardGuildIdAttendanceRoute
  DashboardGuildIdOverviewRoute: typeof DashboardGuildIdOverviewRoute
  DashboardGuildIdSchedulingRoute: typeof DashboardGuildIdSchedulingRoute
  DashboardGuildIdSettingsRoute: typeof DashboardGuildIdSettingsRoute
}

const DashboardGuildIdRouteChildren: DashboardGuildIdRouteChildren = {
  DashboardGuildIdAttendanceRoute: DashboardGuildIdAttendanceRoute,
  DashboardGuildIdOverviewRoute: DashboardGuildIdOverviewRoute,
  DashboardGuildIdSchedulingRoute: DashboardGuildIdSchedulingRoute,
  DashboardGuildIdSettingsRoute: DashboardGuildIdSettingsRoute,
}

const DashboardGuildIdRouteWithChildren =
  DashboardGuildIdRoute._addFileChildren(DashboardGuildIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
